### ISSUE TITLE
Page titles in english are displayed in norwegian

### ISSUE THREAD

**Issue by professoralv** [Alv-no/alv-website#770] opened 2022-10-18 08:34 UTC
This is at least true on the landing page, and it is confusing english google search results.

<img width="311" alt="image" src="https://user-images.githubusercontent.com/73942505/196379496-b8540750-c073-459f-ab03-53ed8be80926.png">

**Comment by professoralv** [comment] 2022-10-18 08:36
Correct page titles are already entered into Sanity.

**Comment by klyngen** [comment] 2022-10-18 10:06
Duplicate of https://github.com/Alv-no/alv-website/issues/703

**Closed by klyngen** 2022-10-18 10:06 UTC
Labels: bug, alv-b
